version: '3.8'

services:
  mongo-api:
    image: mongo:latest
    container_name: mongo-api
    ports:
      - "27018:27017"
    networks:
      - net-api

  poke-api:
    build: ./
    container_name: poke-api
    ports:
      - "3000:3000"
    networks:
      - net-api
    depends_on:
      - mongo-api

networks:
  net-api:
    driver: bridge